name: Build to gh-pages branch

permissions:
  contents: write

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: theme
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
    - name: Set up OCaml
      uses: ocaml/setup-ocaml@v3.2.10
      with:
          ocaml-compiler: 5
    - name: Setup Forester
      run : |
        opam install forester
        eval $(opam env)
        forester build forest.toml

    - name: Peek
      run: tree -L 3
      
    - name: Deploy pages
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/main'
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        publish_dir: ./output
        