name: Build to gh-pages branch

permissions:
  contents: write

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'theme'
        token: ${{ secrets.PERSONAL_TOKEN }}
    - name: Set up OCaml
      uses: ocaml/setup-ocaml@v3.2.10
      with:
          ocaml-compiler: 5
    - name: Setup Forester
      run : |
        opam install forester
        eval $(opam env)
        forester build forest.toml
    - name: Remove gitignore
      run: | 
        rm ./.gitignore
        rm ./theme/.gitignore
      
    - name: Deploy pages
      uses: peaceiris/actions-gh-pages@v4.0.0
      with:
        publish_dir: ./output
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        